#!/bin/bash

# =============================================================================
# ARCH LINUX MIGRATION SCRIPT - PURE FLAT LAYOUT (Limine Edition)
# =============================================================================
# Description: Migra il sistema da Btrfs standard a Layout Flat (@, @home, etc.)
#              Aggiorna Fstab e Limine. NON configura Snapper.
# =============================================================================

# --- Colori e Stile ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

# --- Opzioni Btrfs Ottimizzate (Guida 1.4) ---
# Nota: Manteniamo le opzioni performanti per SSD
BTRFS_OPTS="defaults,noatime,compress=zstd:1,discard=async,ssd,space_cache=v2"

log_info() { echo -e "${BOLD}${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

banner() {
        clear
    echo -e "${BOLD}${GREEN}"
    echo "   ___  ___  ___  ______  ___  _____  _____  _____ "
    echo "   |  \/  | / _ \ | ___ \ |  \/  ||  _  ||  _  | "
    echo "   | .  . |/ /_\ \| |_/ / | .  . || | | || | | | "
    echo "   | |\/| ||  _  ||    /  | |\/| || | | || | | | "
    echo "   | |  | || | | || |\ \  | |  | |\ \_/ /\ \_/ / "
    echo "   \_|  |_/\_| |_/\_| \_| \_|  |_/ \___/  \___/  "
    echo -e "            LIMINE & SNAPPER FIX EDITION${NC}"
    echo "   MIGRATOR TO FLAT LAYOUT (CORE ONLY)"
    echo "   Limine Bootloader Support"
    echo -e "${NC}"
    echo "Questo script sposta il sistema in subvolumi (@, @home, @snapshots, @var_log)"
    echo "e aggiorna fstab/limine.conf per il riavvio."
}

# --- Check Root ---
if [ "$EUID" -ne 0 ]; then log_err "Serve root."; fi

banner
echo -n "Procedere con la migrazione del filesystem? [y/N]: "
read confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then log_err "Annullato."; fi

# --- 1. Analisi Sistema ---
ROOT_UUID=$(findmnt -n -o UUID /)
log_info "UUID Root rilevato: $ROOT_UUID"

# --- 2. Gestione Subvolumi ---
log_info "Creazione struttura subvolumi..."

# Root @
if [ ! -d "/@" ]; then
    btrfs subvolume snapshot / /@ || log_err "Impossibile creare snapshot /@"
    log_success "Snapshot root /@ creato."
else
    log_warn "/@ esisteva già."
fi

# Subvolumi Flat
# Creiamo @snapshots anche se non configuriamo snapper ora, per avere il layout pronto
SUBVOLS=("@home" "@snapshots" "@var_log")
for sv in "${SUBVOLS[@]}"; do
    if [ ! -d "/$sv" ]; then
        btrfs subvolume create "/$sv"
        log_success "Creato subvolume /$sv"
    fi
done

# --- 3. Migrazione Dati ---
log_info "Sincronizzazione dati..."

# Home
if [ -z "$(ls -A /@home)" ]; then
    rsync -aAX --info=progress2 /home/ /@home/
    log_success "/home migrata."
fi

# Var Log
if [ -z "$(ls -A /@var_log)" ]; then
    rsync -aAX --info=progress2 /var/log/ /@var_log/
    log_success "/var/log migrata."
fi

# --- 4. Preparazione Mountpoint (FIX FSTAB) ---
log_info "Preparazione mountpoint dentro la NUOVA root (@)..."

# Puliamo i dati vecchi dentro lo snapshot @ per far posto ai mountpoint
rm -rf /@/home/*
rm -rf /@/var/log/*

# FIX ESSENZIALE: Creiamo la directory /.snapshots dentro la nuova root
# Questo assicura che fstab non fallisca al mount, indipendentemente da Snapper
if [ ! -d "/@/.snapshots" ]; then
    mkdir -p /@/.snapshots
    log_success "Directory mountpoint /@/.snapshots creata."
fi
chmod 750 /@/.snapshots

# --- 5. Generazione Fstab ---
log_info "Generazione nuovo /@/etc/fstab..."
cp /etc/fstab /@/etc/fstab.bak

# Rilevamento Boot
BOOT_UUID=$(findmnt -n -o UUID /boot)
if [ -z "$BOOT_UUID" ] || [ "$BOOT_UUID" == "$ROOT_UUID" ]; then
    IS_BOOT_SEPARATE=false
    BOOT_ENTRY="# /boot è una cartella nel subvolume root"
else
    IS_BOOT_SEPARATE=true
    BOOT_ENTRY="UUID=$BOOT_UUID  /boot        vfat     rw,relatime,fmask=0022,dmask=0022,codepage=437,errors=remount-ro 0 2"
fi

cat <<EOF > /@/etc/fstab
# /etc/fstab: static file system information.
# Generated by Migration Script (Flat Layout)

# Root
UUID=$ROOT_UUID  /            btrfs    subvol=@,$BTRFS_OPTS 0 0

# Subvolumi Dati
UUID=$ROOT_UUID  /home        btrfs    subvol=@home,$BTRFS_OPTS 0 0
UUID=$ROOT_UUID  /var/log     btrfs    subvol=@var_log,$BTRFS_OPTS 0 0

# Subvolume Snapshots (Pronto per il futuro)
UUID=$ROOT_UUID  /.snapshots  btrfs    subvol=@snapshots,$BTRFS_OPTS 0 0

# Bootloader
$BOOT_ENTRY
EOF

# Append Swap se esistente
grep "swap" /etc/fstab >> /@/etc/fstab
log_success "Fstab aggiornato."

# --- 6. Aggiornamento Limine ---
log_info "Configurazione Limine..."
LIMINE_CONF="/boot/limine.conf"
[ -f "$LIMINE_CONF" ] && cp "$LIMINE_CONF" "$LIMINE_CONF.bak-migrazione"

# Pulizia argomenti vecchi
CURRENT_CMDLINE=$(cat /proc/cmdline | sed -e 's/root=UUID=[^ ]*//g' -e 's/root=[^ ]*//g' -e 's/rootflags=[^ ]*//g' -e 's/rw//g')

# Gestione Path Kernel
if [ "$IS_BOOT_SEPARATE" = true ]; then
    KERNEL_PATH="boot():/vmlinuz-linux"
    INITRD_PATH="boot():/initramfs-linux.img"
else
    KERNEL_PATH="boot():/@/boot/vmlinuz-linux"
    INITRD_PATH="boot():/@/boot/initramfs-linux.img"
fi

cat <<EOF > "$LIMINE_CONF"
timeout: 5

/Arch Linux (Flat Layout)
    protocol: linux
    kernel_path: $KERNEL_PATH
    module_path: $INITRD_PATH
    cmdline: root=UUID=$ROOT_UUID rw rootflags=subvol=@ $CURRENT_CMDLINE

/Arch Linux (Fallback)
    protocol: linux
    kernel_path: $KERNEL_PATH
    module_path: ${INITRD_PATH%.img}-fallback.img
    cmdline: root=UUID=$ROOT_UUID rw rootflags=subvol=@ $CURRENT_CMDLINE
EOF
log_success "Limine configurato con rootflags=subvol=@."

# --- Fine ---
echo ""
echo -e "${BOLD}${GREEN}MIGRAZIONE COMPLETATA.${NC}"
echo "-----------------------------------------------------"
echo "Il sistema è stato migrato al layout Flat."
echo "Al prossimo riavvio userai il subvolume @ come root."
echo "La cartella /.snapshots è montata e pronta per quando vorrai configurare Snapper."
echo "-----------------------------------------------------"
echo "Riavvia ora: reboot"
