#!/bin/bash

# =============================================================================
# ARCH LINUX MIGRATION SCRIPT - STRICT GUIDELINE ADHERENCE (Limine Version)
# =============================================================================
# Reference: Guida Operativa 1.2, 1.3, 1.4
# Description: Migrazione "a caldo" a layout Flat con ottimizzazioni SSD specifiche.
# Bootloader: Limine (sostituisce GRUB/Systemd-boot della guida)
# =============================================================================

# --- Configurazioni Estetiche ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# --- 1.4 Ottimizzazione Definitiva (Opzioni da Guida) ---
# compress=zstd:1 : Basso impatto CPU
# discard=async   : TRIM in background
# ssd             : Ottimizzazioni allocazione SSD
# noatime         : Evita scritture inutili
# space_cache=v2  : Cache spazio libero performante
BTRFS_OPTS="defaults,noatime,compress=zstd:1,discard=async,ssd,space_cache=v2"

log_info() { echo -e "${BOLD}${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_err() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

banner() {
    clear
    echo -e "${BOLD}${GREEN}"
    echo "   MIGRATOR TO FLAT LAYOUT (STRICT MODE)"
    echo "   Bootloader: LIMINE"
    echo -e "${NC}"
    echo "Questo script applica le modifiche secondo la Guida Operativa 1.2-1.4"
}

# --- Main Logic ---

banner

if [ "$EUID" -ne 0 ]; then
    log_err "Esegui come root."
fi

log_warn "Verranno creati snapshot e modificato fstab/limine.conf."
echo -n "Procedere? [y/N]: "
read confirm
if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    log_err "Annullato."
fi

# Rilevamento UUID Root
ROOT_UUID=$(findmnt -n -o UUID /)
log_info "UUID Root rilevato: $ROOT_UUID"

# --- 1.2 Guida Operativa: Creazione Subvolumi ---

# 1. Creare lo Snapshot Radice
log_info "Creazione snapshot radice /@..."
if [ ! -d "/@" ]; then
    btrfs subvolume snapshot / /@ || log_err "Errore snapshot /@"
    log_success "Snapshot /@ creato."
else
    log_warn "/@ esiste già, proseguo."
fi

# 2. Creare Subvolumi "Flat" Aggiuntivi
SUBVOLS=("@home" "@snapshots" "@var_log")
for sv in "${SUBVOLS[@]}"; do
    if [ ! -d "/$sv" ]; then
        log_info "Creazione subvolume /$sv..."
        btrfs subvolume create "/$sv" || log_err "Errore creazione $sv"
    fi
done

# 3. Migrare i Dati
# Nota: La guida raccomanda rsync -aAXv. 
# Usiamo --info=progress2 per avere un output visivo migliore ma mantenendo -aAX
log_info "Migrazione dati verso i nuovi subvolumi..."

# Migrazione HOME
if [ -z "$(ls -A /@home)" ]; then
    log_info "Eseguo rsync di /home (preserva ACL/XATTRS)..."
    rsync -aAX --info=progress2 /home/ /@home/ || log_err "Rsync /home fallito"
    log_success "/home migrata in /@home."
fi

# Migrazione VAR/LOG
if [ -z "$(ls -A /@var_log)" ]; then
    log_info "Eseguo rsync di /var/log..."
    rsync -aAX --info=progress2 /var/log/ /@var_log/ || log_err "Rsync /var/log fallito"
    log_success "/var/log migrata in /@var_log."
fi

# 4. Svuotare i Vecchi Mountpoint (dentro lo snapshot @)
# La guida dice: "la directory /home originale (che ora si trova dentro /@/home) deve essere svuotata"
log_info "Pulizia dei mountpoint all'interno di /@..."
rm -rf /@/home/*
rm -rf /@/var/log/*
log_success "Mountpoint /@/home e /@/var/log svuotati."

# --- 1.3 Riconfigurazione di /etc/fstab ---

log_info "Generazione nuovo /@/etc/fstab..."
cp /etc/fstab /@/etc/fstab.bak # Backup

# Rilevamento Boot
BOOT_UUID=$(findmnt -n -o UUID /boot)
if [ -z "$BOOT_UUID" ] || [ "$BOOT_UUID" == "$ROOT_UUID" ]; then
    # Boot folder dentro root
    BOOT_ENTRY="# /boot è parte del filesystem root (cartella)"
    IS_BOOT_SEPARATE=false
else
    # Partizione EFI separata
    BOOT_ENTRY="UUID=$BOOT_UUID  /boot        vfat     rw,relatime,fmask=0022,dmask=0022,codepage=437,errors=remount-ro 0 2"
    IS_BOOT_SEPARATE=true
fi

# Scrittura Fstab con le opzioni del punto 1.4
cat <<EOF > /@/etc/fstab
# /etc/fstab: static file system information.
# Generated by Migration Script following Guide 1.3/1.4

# Root Subvolume
UUID=$ROOT_UUID  /            btrfs    subvol=@,$BTRFS_OPTS 0 0

# Subvolumi Aggiuntivi
UUID=$ROOT_UUID  /home        btrfs    subvol=@home,$BTRFS_OPTS 0 0
UUID=$ROOT_UUID  /.snapshots  btrfs    subvol=@snapshots,$BTRFS_OPTS 0 0
UUID=$ROOT_UUID  /var/log     btrfs    subvol=@var_log,$BTRFS_OPTS 0 0

# Partizione EFI / Boot
$BOOT_ENTRY

# Swap (se presente nel vecchio fstab, aggiungere manualmente qui sotto)
EOF

# Recupero swap se esiste
grep "swap" /etc/fstab >> /@/etc/fstab
log_success "Nuovo fstab creato in /@/etc/fstab"

# --- Aggiornamento Bootloader (Adattamento LIMINE) ---
# La guida dice: "Il bootloader deve essere informato... rootflags=subvol=@"
log_info "Aggiornamento configurazione Limine..."

LIMINE_CONF="/boot/limine.conf"
if [ ! -f "$LIMINE_CONF" ]; then
    log_warn "File $LIMINE_CONF non trovato. Creazione di un config base."
    touch "$LIMINE_CONF"
else
    cp "$LIMINE_CONF" "$LIMINE_CONF.bak-migrazione"
fi

# Recupera cmdline attuale pulita
CURRENT_CMDLINE=$(cat /proc/cmdline | sed -e 's/root=UUID=[^ ]*//g' -e 's/root=[^ ]*//g' -e 's/rootflags=[^ ]*//g' -e 's/rw//g')

# Gestione path kernel per Limine
if [ "$IS_BOOT_SEPARATE" = true ]; then
    # Se /boot è partizione a parte, i file sono alla radice della partizione
    KERNEL_PATH="boot():/vmlinuz-linux"
    INITRD_PATH="boot():/initramfs-linux.img"
else
    # Se /boot è cartella, ora è dentro @/boot
    KERNEL_PATH="boot():/@/boot/vmlinuz-linux"
    INITRD_PATH="boot():/@/boot/initramfs-linux.img"
fi

# Scrittura Configurazione Limine
cat <<EOF > "$LIMINE_CONF"
timeout: 5

/Arch Linux (Flat Layout)
    protocol: linux
    kernel_path: $KERNEL_PATH
    module_path: $INITRD_PATH
    # Qui applichiamo la regola della guida: rootflags=subvol=@
    cmdline: root=UUID=$ROOT_UUID rw rootflags=subvol=@ $CURRENT_CMDLINE

/Arch Linux (Fallback)
    protocol: linux
    kernel_path: $KERNEL_PATH
    module_path: ${INITRD_PATH%.img}-fallback.img
    cmdline: root=UUID=$ROOT_UUID rw rootflags=subvol=@ $CURRENT_CMDLINE
EOF

log_success "Limine aggiornato con rootflags=subvol=@."
echo ""
echo -e "${BOLD}${GREEN}OPERAZIONE COMPLETATA.${NC}"
echo "Riavvia il sistema e verifica con 'findmnt /' che subvol=/@ sia attivo."
